import Head from 'next/head'
import Main from "../components/main"
import About from "../components/about"
import Skills from "../components/skills"
import Projects from "../components/Projects"
import Contact from "../components/Contact"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Otiz Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Main />
    <About />
    <Skills /> 
    <Projects />
   <Contact />
    </div>
  )
}


